# Generated by Django 3.1 on 2021-09-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
